# (Optional) Name of the bot.
# If not specified, name is the config file name with the extension stripped.
# Bot names need to be unique for each instance of botmand.
name: foobot

# (Mandatory) Path to the bot executable
handler: /path/to/executable

# (Optional) List of environment variables to be set in each bot instance.
environment:
  DEBUG: false
  API_KEY: xxyyzz

# (Optional) List of triggers (regexes) which activate this bot.
# If not specified, bot is triggered by any message on the channel.
triggers:
  - hello                 # Case-sensitive regex match
  - (?i)anybody there\?   # Case-insensitive regex match

# (Optional) Flag to control if bot is triggered only by messages where it is
# explicitly mentioned.
# This is the default behaviour.
#
# NOTE: This flag applies only to messages that trigger the bot. Once a bot is
#       active in a thread or a channel, it will receive all messages (by
#       default) in the thread or channel until it terminates.
#       See the "direct-messages-only" flag below to change that.
#
direct-message-triggers-only: true

# (Optional) Flag to control if bot only receives messages where it is
# explicitly mentioned.
#
# NOTE: This flag is set to false by default. BotManD bots are configured by
#       default to receive ALL messages in the conversation once triggered.
#
# Setting this flag to true makes the bot behave like a traditional bot that
# only receives direct messages, but it is more useful for a conversational bot
# to read all messages and decide for itself which ones it wants to respond to.
direct-messages-only: false  ## NOTE: When unset, defaults to "false"

# (Optional) Have bot only respond to messages in channels listed here.
# If not specified, respond on all channels the bot has been invited to.
channels:
  - general

# (Optional) Flag to control if messages are prefixed by sender userID.
# Useful if the bot needs to distinguish between participants in conversation.
# Default is not to prefix the username.
prefix-username: false

# (Optional) Flag to control if bot responds in a thread.
# Default is "false", which makes the bot respond in the channel (channel-bot
# mode). If set to true, a new conversation, i.e., a new instance of the bot,
# is started for every trigger, and the bot's responses are posted in a thread.
# This mode is more suitable for short-lived transactional bots.
# More than one threaded bot can be active in a channel at a time.
#
# NOTE: You almost always want a trigger to be specified when "threaded" is
# true. Otherwise, you will end up with a new bot being started for every
# message.
#
threaded: false
